### PR TITLE
We Should Prefix Transitions

### PR DESCRIPTION
**Pull request by danielhickman**
Source: https://developer.mozilla.org/en-US/docs/Web/CSS/transition#Browser_compatibility

### CODE REVIEW

**Comment by danielhickman** [comment]
Oops it seems you have two pages on the GitHub. I was looking for my edit so I could add the Safari comment too.

This is right:
https://github.com/davidhund/shouldiprefix/blob/master/_posts/2013-03-04-transitions.md

But it doesn't show on the website. http://shouldiprefix.com/#transitions

**Comment by davidhund** [comment]
I have dropped prefixes for Transitions [some time ago](https://github.com/davidhund/shouldiprefix/commit/ecdf8f20308814e1de58794294b75ef732b5feda).

The reason is that I list prefixes for browser *until 3 versions back*. For desktop browsers Safari 6 (iOS 6.1) was the latest browser still needing `-webkit-`, so I dropped it.

However: Blackberry 7 and Android UC 9.9 still require `-webkit-` so I might re-add that single prefix for those browsers.

I should really  work with something like Autoprefixr and their browserlist, e.g. `> 1%, last 2 versions` or something.

I will not add `-moz-` and `-o-` since they're definitely not needed.

The other thing you must know is that I keep `master` up to date, but sync with `gh-pages` which turns up on the site :-)

**Comment by danielhickman** [comment]
Oh okay then. I was confused because I thought it had the prefixes for 100% compat (well, ~100)

**Comment by davidhund** [comment]
Nope, not 100%, more like ["For Modern Browsers"](http://shouldiprefix.com/disclaimer.html) :-)

**Pull request closed without merging**
